update config

diff --git a/.github/workflows/config.yml b/.github/workflows/config.yml
--- a/.github/workflows/config.yml
+++ b/.github/workflows/config.yml
@@ -45,6 +45,7 @@ jobs:
           fi
 
       - name: Run Selected UI-tests
+        id: run_tests
         env:
           VALID_LOGIN: ${{secrets.VALID_LOGIN}}
           VALID_PASSWORD: ${{secrets.VALID_PASSWORD}}
@@ -52,10 +53,52 @@ jobs:
           EXPECTED_PROFILE_TITLE:  ${{secrets.EXPECTED_PROFILE_TITLE}}
           EXPECTED_ERROR_MESSAGE: ${{secrets.EXPECTED_ERROR_MESSAGE}}
         run: |
-          if [ -z "${{ steps.set_marker.outputs.MARKER }}" ]; then
-            echo "Запуск ВСЕХ тестов..."
-            pytest
-          else
-            echo "Запуск тестов с маркером: ${{ steps.set_marker.outputs.MARKER }}..."
-            pytest -m "${{ steps.set_marker.outputs.MARKER }}"
+          TESTS_TYPE= "${{github.event.inputs.test_type}}"
+          ALLURE_RESULTS_DIR =allure-results
+
+          echo "ALLURE_REPORT_URL=${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
+          if [ "$TEST_TYPE" == "skip_tests" ]; then
+            echo "::notice file=info.txt::Tests skipped by user choice."
+            exit 0
           fi
+
+          rm -rf $ALLURE_RESULTS_DIR
+          mkdir -p $ALLURE_RESULTS_DIR
+
+          echo "Starting tests for type: $TEST_TYPE"
+          
+          if [ "$TEST_TYPE" == "all" ]; then
+            pytest --alluredir=$ALLURE_RESULTS_DIR
+          elif [ "$TEST_TYPE" == "positive" ]; then
+            pytest -m positive --alluredir=$ALLURE_RESULTS_DIR
+          elif [ "$TEST_TYPE" == "negative" ]; then
+            pytest -m negative --alluredir=$ALLURE_RESULTS_DIR
+          fi
+
+          exit_code=$?
+          if [ $exit_code -ne 0 ]; then
+            echo "::warning file=run_tests.sh,line=1::Pytest completed with failures (Exit code $exit_code)."
+            # Продолжаем, чтобы сгенерировать отчет
+          fi
+          
+      - name: Build Allure Report
+        if: always()
+        uses: simple-actions/allure-report-action@v1.0.0
+        with:
+          allure_results_path: allure-results
+          gh-pages_branch: gh-pages
+
+      - name: Upload Allure Report
+        if: always()
+        uses: actions/upload-artifact@v3
+        with:
+          name: allure-results-${{ github.event.inputs.test_type }}
+          path: allure-results
+          
+      - name: Upload Allure Report
+        if: always()
+        uses: actions/upload-artifact@v3
+        with:
+          name: allure-report-${{ github.event.inputs.test_type }}
+          path: allure-report
+        
